Add configs
gridsuite/merge-orchestrator-server pull request #29
Opened 2020-12-30 09:13 UTC by ChamseddineBhd

2021-01-08 10:28 UTC, FranckLecuyer requested changes

2021-01-08 10:28 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/merge/orchestrator/server/repositories/MergeRepository.java
> +    void deleteByProcess(@Param("process") String process);
Is the @Param annotation required ?

2021-01-08 10:28 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorService.java
> +        return tsos.stream().anyMatch(ts -> ts.getSourcingActor().equals(tso) || ts.getAlternativeSourcingActor().equals(tso))
Maybe a method for matching the sourcingActor or alternativeSourcingActor ?

2021-01-08 10:28 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorService.java
> +                    if (processConfig.getTsos().stream().anyMatch(ts -> ts.getSourcingActor().equals(tso) || ts.getAlternativeSourcingActor().equals(tso))) {
Calling the method defined above

2021-01-08 10:28 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorService.java
> +        if (processConfig.getTsos().stream().anyMatch(ts -> ts.getSourcingActor().equals(tso) || ts.getAlternativeSourcingActor().equals(tso))) {
Calling the method defined above

2021-01-08 13:53 UTC, ChamseddineBhd commented on src/main/java/org/gridsuite/merge/orchestrator/server/repositories/MergeRepository.java
> +    void deleteByProcess(@Param("process") String process);
yes it's optional

2021-01-08 14:15 UTC, FranckLecuyer approved these changes

2021-01-14 14:59 UTC, jonenst requested changes
split PR in multiple PRs for different things

2021-01-25 16:39 UTC, jonenst approved these changes

2021-01-25 16:39 UTC, merged