[WIP] Replacing missing or invalid igms
gridsuite/merge-orchestrator-server pull request #33
Opened 2021-01-26 14:39 UTC by FranckLecuyer

2021-02-02 16:38 UTC, niconoir requested changes

2021-02-03 07:55 UTC, FranckLecuyer commented on src/main/resources/replaceIGM.groovy
> +    newDate = zonedDate.minusDays(3)
Done

2021-02-03 17:36 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorService.java
> +            igmRepository.updateReplacingIgm(config.getProcess(), processDt, tso,
Modifications done

2021-02-05 17:50 UTC, niconoir approved these changes

2021-02-17 15:39 UTC, merged