[WIP] Delete network igms when deleting process config
gridsuite/merge-orchestrator-server pull request #38
Opened 2021-03-11 18:12 UTC by SlimaneAmar

2021-03-12 15:47 UTC, FranckLecuyer requested changes

2021-03-12 15:47 UTC, FranckLecuyer commented on src/test/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorIT.java
> +        assertEquals(4, igmRepository.findAll().size());
duplicate assert

2021-03-12 16:05 UTC, SlimaneAmar commented on src/test/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorIT.java
> +        assertEquals(4, igmRepository.findAll().size());
Done

2021-03-15 15:08 UTC, niconoir approved these changes

2021-03-16 08:03 UTC, FranckLecuyer approved these changes

2021-03-19 14:51 UTC, merged