Relax loadflow parameters on cgm
gridsuite/merge-orchestrator-server pull request #43
Opened 2021-04-08 13:10 UTC by FranckLecuyer

2021-04-22 15:31 UTC, ChamseddineBhd requested changes

2021-04-22 15:31 UTC, ChamseddineBhd commented on src/main/java/org/gridsuite/merge/orchestrator/server/LoadFlowService.java
> +    private boolean isMainComponentConverging(LoadFlowResult result) {
isMainComponentConverg**ed**

2021-04-23 07:23 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/merge/orchestrator/server/LoadFlowService.java
> +    private boolean stepRun(String step, LoadFlowParameters params, String uri, List<UUID> networksIds) {
Done

2021-04-23 07:24 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/merge/orchestrator/server/LoadFlowService.java
> +    private boolean isMainComponentConverging(LoadFlowResult result) {
Done

2021-04-26 08:24 UTC, ChamseddineBhd approved these changes

2021-04-26 09:37 UTC, merged